#!/usr/bin/env node

import {
  chmod,
  lstat,
  mkdir,
  readFile,
  readdir,
  rm,
  writeFile,
} from "node:fs/promises";
import { dirname, join, relative, resolve, sep } from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const defaultRoot = resolve(fileURLToPath(new URL("../..", import.meta.url)));
const generatedMarker = "<!-- Code generated by tools/codex-runtime/sync-skills.mjs; DO NOT EDIT. -->";
const namePattern = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

// These skills have intentionally hand-authored Codex contracts. Every other
// canonical skill receives a generated runtime adapter and a packaged copy of
// its canonical workflow/resources.
export const codexOverrides = new Set([
  "deliver",
  "implement",
  "init",
  "modes",
  "pipeline",
  "recover",
  "setup",
  "update",
  "validate",
]);

export const opencodeOverrides = new Set([
  "background",
  "cross-repo",
  "recover",
  "setup",
  "tmux",
  "update",
]);

const codexSpecialMappings = new Map([
  ["bootstrap", "Initialize AGENTS.md and native Codex project conventions; use CLAUDE.md only when explicitly requested for compatibility."],
  ["background", "Use Codex subagents for bounded background work. Never launch or require the `claude` binary."],
  ["clickup", "Store persistent values in the Codex-native Team Harness configuration. Preserve all opaque keys and never print credentials."],
  ["cross-repo", "Use only repository paths and external reads authorized by the operator. Delegate useful independent repository work with explicit ownership under native permissions."],
  ["diagram", "Create the diagram directly in Main using the packaged Excalidraw workflow; do not dispatch a Claude orchestrator."],
  ["d2-diagram", "Author the `.d2` source directly. Treat D2 CLI rendering as optional and report when the executable is unavailable."],
  ["excalidraw-diagram", "Use the packaged schema, templates, and renderer directly; preserve its render-validation loop when dependencies are available."],
  ["gcp-costs", "Default to read-only GCP inspection. Require native permission and explicit operator scope before any external command."],
  ["gcp-infra", "Keep read-and-plan as the default and use native `security` and `qa` reviewers for a prepared change. Follow canonical scoped authorization: reuse clear approval for the unchanged plan, ask only for a missing decision, and preserve native permissions."],
  ["inline", "Treat inline as a Team Harness working preference only. It cannot change Codex's system collaboration mode, sandbox, or approval policy."],
  ["kg", "Use the configured Memory MCP when available; otherwise report the missing native dependency without substituting another store."],
  ["learn-english", "Read and update only the Codex-native Team Harness configuration through its packaged configuration helper."],
  ["likec4-diagram", "Author the `.c4` source directly. Treat LikeC4 rendering as optional and report when the CLI is unavailable."],
  ["lint", "Audit Codex plugin skills, generated agents, native hooks, and configuration paths; do not inspect or repair a Claude Code installation."],
  ["mcp-optimize", "Inspect Codex MCP registrations and config rather than Claude connector files. Preserve secrets and use existing scoped authorization and native permissions for writes."],
  ["obsidian-bases", "Resolve vault settings from Codex-native Team Harness configuration or explicit operator input, never from a Claude-only config path."],
  ["obsidian-cli", "Resolve vault settings from Codex-native Team Harness configuration or explicit operator input, never from a Claude-only config path."],
  ["pipelines", "Resolve workspace settings from the Codex-native Team Harness configuration and render state read-only."],
  ["research-code", "Use Codex explorers or other bounded subagents only when independent lanes are useful and allowed; Main consolidates all evidence."],
  ["save-session", "Use the shared workspace skill with Codex-native settings and reuse the operator's existing authorization for the scoped handoff write."],
  ["resume-session", "Resolve workspace settings from the Codex-native Team Harness configuration and remain strictly read-only."],
  ["review-pr", "Main coordinates native Codex PR-review subagents and consolidates their advisory returns; no nested orchestrator or mandatory consolidator. Load canonical phase references progressively and preserve immutable capture, selected coverage, independent verification and approval before publishing. When Read/Glob/Grep are absent, bounded non-mutating exec_command calls are the native filesystem-read transport; this alone never requires setup, update or restart. Verify effective permissions at dispatch: sandbox_mode read-only in a role TOML is a default and may be overridden by parent settings; it does not by itself deny network/MCP writes or delegation. Use the role's scoped read contract and the available native permission boundary, reporting enforcement gaps honestly. Read only supplied artifacts and verified regular worktree leaves. Main may request one focused correction for a missing return field or mistaken optional path at the same snapshot, preserving successful work. Mismatched identity, unreadable required evidence or captured-integrity failure makes that evidence unavailable. Remote PR movement preserves completed work: reconcile only affected findings, disclose reviewed scope and retain the operator's publication choice. Failed publication keeps the run for resume. Unless base policy turns verification off, dispatch the independent verifier and validate assessments with apply-verification; the helper preserves findings, while Main owns evidence-backed dispositions and the all-finding ledger. Report verified k/n and absent coverage honestly."],
  ["tmux", "When the operator explicitly requests external sessions, launch `codex`, never `claude`, and preserve native permission prompts and recoverable session naming."],
  ["todo", "Store persistent values in the Codex-native Team Harness configuration and preserve unrelated keys."],
  ["trace", "Resolve workspace and pricing settings from the Codex-native Team Harness configuration and remain read-only."],
]);

const opencodeSpecialMappings = new Map([
  ["review-pr", "Main coordinates native OpenCode PR-review subagents and consolidates advisory results; no required consolidator. Check only selected roles and their effective native permission rules. The installed compatibility projection uses permission with default deny and read/glob/grep allow, excluding bash/task, edit and external writes. Check the active OpenCode version/config schema before translating newer names such as permissions, shell or subagent; never inject those fields into a legacy configuration. Preserve OPENCODE_CONFIG_DIR/project scope and the independent writing authority of implementers. Native enforcement and model-backed dispatch must be verified separately from Go/JavaScript projection tests. Follow the canonical phase references progressively; do not require Claude paths or binaries."],
  ["bootstrap", "Initialize `AGENTS.md` and opencode-native project conventions unless the operator explicitly requests a Claude compatibility file."],
  ["clickup", "Store persistent values in the opencode-native Team Harness configuration. Preserve all opaque keys and never print credentials."],
  ["diagram", "Create the diagram through the packaged Excalidraw workflow; do not dispatch a Claude agent."],
  ["gcp-costs", "Default to read-only GCP inspection and require explicit scope before calling `gcloud`."],
  ["gcp-infra", "Keep read-and-plan as the default and use native security and QA reviewers for a prepared change. Follow canonical scoped authorization: reuse clear approval for the unchanged plan, ask only for a missing decision, and preserve native permissions."],
  ["kg", "Use the configured Memory MCP when available; otherwise report the missing native dependency."],
  ["learn-english", "Read and update only the opencode-native Team Harness configuration."],
  ["lint", "Audit opencode-projected agents, skills, commands, and native configuration; do not inspect a Claude Code installation."],
  ["mcp-optimize", "Inspect opencode MCP registrations and configuration rather than Claude connector files."],
  ["obsidian-bases", "Resolve vault settings from opencode-native Team Harness configuration or explicit operator input."],
  ["obsidian-cli", "Resolve vault settings from opencode-native Team Harness configuration or explicit operator input."],
  ["pipelines", "Resolve workspace settings from opencode-native Team Harness configuration and render state read-only."],
  ["save-session", "Use the shared workspace skill with opencode-native settings and reuse the operator's existing authorization for the scoped handoff write."],
  ["resume-session", "Resolve workspace settings from opencode-native Team Harness configuration and remain read-only."],
  ["todo", "Store persistent values in opencode-native Team Harness configuration and preserve unrelated keys."],
  ["trace", "Resolve workspace and pricing settings from opencode-native Team Harness configuration and remain read-only."],
]);

export const sharedPipelineScripts = [
  "bounded-command.mjs",
  "cli-entrypoint.mjs",
  "code-hygiene.mjs",
  "commit-integrity.mjs",
  "control-plane.mjs",
  "control-plane-specialist.mjs",
  "quality-lib.mjs",
  "quality-runner.mjs",
  "test-transition.mjs",
  "worktree-dependencies.mjs",
  "workspace-preflight.mjs",
  "workspace-identity.mjs",
  "herdr-message.mjs",
  "openspec-events.mjs",
  "review-surface.mjs",
];

const sharedPipelinePolicies = ["openspec-policy.json"];

// docs/ files the packaged agent bodies instruct reading at runtime; the
// Codex package must carry them so those reads resolve on an installed tree.
export const claudePackageDocs = [
  "agent-authoring.md",
  "code-comments.md",
  "code-hygiene-gate.md",
  "context7-usage.md",
  "gcp-infra.md",
  "permission-provisioning.md",
  "pipeline-lanes.md",
  "plan-shards.md",
  "testing.md",
  "verification-packet.md",
  "worktree-discipline.md",
];

function yamlString(value) {
  return JSON.stringify(value);
}

function humanize(name) {
  return name.split("-").map(part => part[0].toUpperCase() + part.slice(1)).join(" ");
}

function parseCanonicalSkill(bytes, expectedName) {
  const text = bytes.toString("utf8").replace(/^\uFEFF/, "").replace(/\r\n?/g, "\n");
  const match = text.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);
  if (!match) throw new Error(`invalid frontmatter: skills/${expectedName}/SKILL.md`);
  const fields = new Map();
  for (const line of match[1].split("\n")) {
    const field = line.match(/^([a-zA-Z0-9_-]+):\s*(.*)$/);
    if (!field) continue;
    let value = field[2].trim();
    if (value.startsWith('"') && value.endsWith('"')) value = value.slice(1, -1);
    fields.set(field[1], value);
  }
  if (fields.get("name") !== expectedName) {
    throw new Error(`skill name mismatch: ${expectedName} != ${fields.get("name")}`);
  }
  const description = fields.get("description");
  if (!description) throw new Error(`missing description: skills/${expectedName}/SKILL.md`);
  return {
    body: match[2].trimEnd(),
    description,
    explicitOnly: fields.get("disable-model-invocation") === "true",
  };
}

function projectedSkillName(name, runtime) {
  // OpenCode has a flat skill namespace; leave the upstream Sentry name intact.
  return runtime === "opencode" && name === "find-bugs" ? "th-find-bugs" : name;
}

function renderAdapter(name, canonical, runtime) {
  const codex = runtime === "codex";
  const nativeName = projectedSkillName(name, runtime);
  const mapping = (codex ? codexSpecialMappings : opencodeSpecialMappings).get(name)
    ?? `Execute the capability directly with ${codex ? "Codex" : "opencode"}-native tools and the current permission policy.`;
  const invocation = codex ? `$team-harness:${name}` : nativeName;
  const example = codex
    ? `Examples written as \`/th:${name}\` name the same capability; do not try to execute them as shell commands.`
    : `Examples written as \`/th:${name}\` name the same capability; interpret them as examples rather than requiring Claude Code.`;
  const configPath = codex
    ? "${CODEX_HOME:-$HOME/.codex}/.team-harness.json"
    : "${OPENCODE_CONFIG_DIR:-$HOME/.config/opencode}/.team-harness.json";
  const frontmatter = canonical.explicitOnly && !codex
    ? `---\nname: ${nativeName}\ndescription: ${yamlString(canonical.description)}\nmetadata:\n  opencode/autoinvoke: "false"\n---`
    : `---\nname: ${nativeName}\ndescription: ${yamlString(canonical.description)}\n---`;
  return `---
${frontmatter.slice(4)}

${generatedMarker}

# ${humanize(name)}

This is the ${codex ? "Codex" : "opencode"} projection of the canonical Team Harness \`${name}\`
workflow. Before acting, read \`canonical.md\` completely and load only the
supporting resources it routes to.

## ${codex ? "Codex" : "opencode"} runtime adapter

These rules override contradictory runtime-specific wording in the canonical
workflow:

1. Treat the live operator request for \`${invocation}\` as the canonical
   \`$ARGUMENTS\` value. ${example}
2. Keep the current primary thread as coordinator. A canonical instruction to
   invoke \`th:orchestrator\` means execute that routing decision in the current
   primary thread. Never spawn a persistent or nested orchestrator.
3. Translate Claude tool names to the closest native ${codex ? "Codex" : "opencode"} tools. Delegate
   only bounded work to available native agents when delegation is allowed and
   materially useful. Gate approval and consolidation stay in the primary thread.
4. Resolve persistent settings from
   \`${configPath}\`. Never depend on a Claude
   Code installation, \`~/.claude\`, the \`claude\` binary, or Claude plugin
   cache paths. Use packaged files relative to this skill directory.${codex ? "" : " Canonical agent reference documents (`agents/ref-*.md` and documents in agent subdirectories, except README.md) resolve under `th-references/agents/...` in that config root, including links with relative prefixes. Invocable agent definitions remain under `agents/`."}
5. Preserve every canonical safety boundary, read-only default, confirmation
   gate, secret rule, and outward-write approval. Native ${codex ? "Codex" : "opencode"} sandbox and
   permission policy remain authoritative.
6. ${mapping}

Execute the requested workflow after applying this adapter. Do not merely
summarize the canonical instructions.
`;
}

function renderOpenAI(name, canonical) {
  const short = `Team Harness ${humanize(name)} workflow`;
  return `interface:
  display_name: ${yamlString(`Team Harness ${humanize(name)}`)}
  short_description: ${yamlString(short.slice(0, 64))}
  default_prompt: ${yamlString(`Use $team-harness:${name} for this request.`)}
${canonical.explicitOnly ? "policy:\n  allow_implicit_invocation: false\n" : ""}`;
}

async function walkFiles(base, current = base, { symbolicLinks = "reject" } = {}) {
  const result = new Map();
  let entries;
  try {
    entries = await readdir(current, { withFileTypes: true });
  } catch (error) {
    if (error?.code === "ENOENT") return result;
    throw error;
  }
  entries.sort((a, b) => a.name.localeCompare(b.name));
  for (const entry of entries) {
    const absolute = join(current, entry.name);
    const rel = relative(base, absolute).split(sep).join("/");
    const stat = await lstat(absolute);
    if (stat.isSymbolicLink()) {
      if (symbolicLinks === "include") {
        // Keep the link as an entry for ownership classification, but never
        // follow it. Source trees and guarded destinations still use the
        // default rejection mode.
        result.set(rel, null);
        continue;
      }
      throw new Error(`refusing symbolic link: ${absolute}`);
    }
    if (stat.isDirectory()) {
      if (entry.name === "__pycache__" || entry.name === "node_modules" || entry.name === ".venv") continue;
      for (const [child, bytes] of await walkFiles(base, absolute, { symbolicLinks })) {
        result.set(child, bytes);
      }
    } else if (stat.isFile() && !entry.name.endsWith(".pyc")) {
      result.set(rel, await readFile(absolute));
    }
  }
  return result;
}

async function canonicalNames(rootDir) {
  const sourceRoot = join(rootDir, "skills");
  const entries = await readdir(sourceRoot, { withFileTypes: true });
  const names = [];
  for (const entry of entries) {
    if (!entry.isDirectory() || !namePattern.test(entry.name)) continue;
    try {
      const stat = await lstat(join(sourceRoot, entry.name, "SKILL.md"));
      if (stat.isFile()) names.push(entry.name);
    } catch (error) {
      if (error?.code !== "ENOENT") throw error;
    }
  }
  return names.sort();
}

async function expectedProjection(rootDir, name, runtime) {
  const sourceDir = join(rootDir, "skills", name);
  const sourceFiles = await walkFiles(sourceDir);
  const canonicalBytes = sourceFiles.get("SKILL.md");
  if (!canonicalBytes) throw new Error(`missing canonical skill: ${name}`);
  const canonical = parseCanonicalSkill(canonicalBytes, name);
  const expected = new Map([
    ["SKILL.md", Buffer.from(renderAdapter(name, canonical, runtime))],
    ["canonical.md", Buffer.from(`${canonical.body}\n`)],
  ]);
  if (runtime === "codex") {
    expected.set("agents/openai.yaml", Buffer.from(renderOpenAI(name, canonical)));
  }
  for (const [rel, bytes] of sourceFiles) {
    if (rel === "SKILL.md" || rel === "agents/openai.yaml") continue;
    expected.set(rel, bytes);
  }
  return expected;
}

async function isGenerated(targetDir) {
  try {
    const skill = await readFile(join(targetDir, "SKILL.md"), "utf8");
    return skill.includes(generatedMarker);
  } catch (error) {
    if (error?.code === "ENOENT") return false;
    throw error;
  }
}

async function projectionMatches(targetDir, expected) {
  const actual = await walkFiles(targetDir);
  if (actual.size !== expected.size) return false;
  for (const [rel, bytes] of expected) {
    if (!actual.get(rel)?.equals(bytes)) return false;
  }
  return true;
}

async function syncProjection({ check, rootDir, names, runtime, targetRoot, overrides }) {
  for (const override of overrides) {
    if (!names.includes(override)) throw new Error(`${runtime} override has no canonical skill: ${override}`);
  }

  let stale = false;
  for (const name of names) {
    if (overrides.has(name)) continue;
    const targetDir = join(targetRoot, projectedSkillName(name, runtime));
    const expected = await expectedProjection(rootDir, name, runtime);
    if (await projectionMatches(targetDir, expected)) continue;
    stale = true;
    if (check) {
      process.stderr.write(`stale ${runtime} skill: ${name}\n`);
      continue;
    }
    try {
      const stat = await lstat(targetDir);
      if (stat.isSymbolicLink() || !stat.isDirectory() || !(await isGenerated(targetDir))) {
        throw new Error(`refusing to replace unmanaged ${runtime} skill: ${targetDir}`);
      }
      await rm(targetDir, { recursive: true });
    } catch (error) {
      if (error?.code !== "ENOENT") throw error;
    }
    for (const [rel, bytes] of expected) {
      const target = join(targetDir, rel);
      await mkdir(dirname(target), { recursive: true });
      await writeFile(target, bytes);
    }
  }

  const targetEntries = await readdir(targetRoot, { withFileTypes: true });
  const projectedNames = new Set(names.map(name => projectedSkillName(name, runtime)));
  for (const entry of targetEntries) {
    if (!entry.isDirectory() || projectedNames.has(entry.name)) continue;
    const targetDir = join(targetRoot, entry.name);
    if (!(await isGenerated(targetDir))) continue;
    stale = true;
    if (check) process.stderr.write(`stale generated skill: ${entry.name}\n`);
    else await rm(targetDir, { recursive: true });
  }

  if (check && stale) throw new Error(`${runtime} skill projections are stale`);
  return names.filter(name => !overrides.has(name));
}

export async function syncSharedSetupAssets({ check, rootDir }) {
  const source = join(rootDir, "skills/setup/scripts/manage_github_identities.py");
  const bytes = await readFile(source);
  const targets = [
    join(rootDir, "plugins/team-harness/skills/setup/scripts/manage_github_identities.py"),
    join(rootDir, "installer-assets/opencode-skills/setup/scripts/manage_github_identities.py"),
  ];
  let stale = false;
  for (const target of targets) {
    let current;
    let currentMode;
    try {
      const [bytesAtTarget, targetStat] = await Promise.all([
        readFile(target),
        lstat(target),
      ]);
      current = bytesAtTarget;
      currentMode = targetStat.mode & 0o777;
    } catch (error) {
      if (error?.code !== "ENOENT") throw error;
    }
    const bytesMatch = current?.equals(bytes) ?? false;
    // Windows does not expose Git's executable bit through Node's POSIX mode
    // field. Keep the mode assertion on POSIX hosts, while still checking
    // bytes on every platform.
    const modeMatches = process.platform === "win32" || currentMode === 0o755;
    if (bytesMatch && modeMatches) continue;
    stale = true;
    if (check) {
      const drift = [!bytesMatch && "content", !modeMatches && "mode"]
        .filter(Boolean)
        .join("+");
      process.stderr.write(`stale shared setup asset (${drift}): ${relative(rootDir, target)}\n`);
      continue;
    }
    await mkdir(dirname(target), { recursive: true });
    if (!bytesMatch) await writeFile(target, bytes, { mode: 0o755 });
    await chmod(target, 0o755);
  }
  if (check && stale) throw new Error("shared setup assets are stale");
}

function isOpenCodeScratchBundle(relativePath) {
  return /^ts\/dist\/(?:opencode-plugin|[^/]+\.opencode)\.cjs$/.test(relativePath);
}

function isProjectedSourcePath(relativePath, files, allowlist, excluded = () => false) {
  const prefix = `${relativePath}/`;
  for (const sourcePath of files.keys()) {
    if (allowlist !== null && !allowlist.has(sourcePath)) continue;
    if (excluded(sourcePath)) continue;
    if (sourcePath === relativePath || sourcePath.startsWith(prefix)) return true;
  }
  return false;
}

async function assertSafeLinkRemoval(rootDir, target) {
  await assertSafeDestinationPath(rootDir, dirname(target), "directory");
  const stat = await lstat(target);
  if (!stat.isSymbolicLink()) throw new Error(`refusing to remove non-symbolic-link package asset: ${target}`);
}

/** Synchronize curated Claude assets; check mode reports drift without writing. */
export async function syncClaudePackageAssets({ check, rootDir }) {
  const projections = [
    [join(rootDir, ".claude-plugin"), join(rootDir, "plugins/team-harness/.claude-plugin"), new Set(["plugin.json", "hooks.json"])],
    [join(rootDir, "agents"), join(rootDir, "plugins/team-harness/agents"), null],
    [join(rootDir, "hooks"), join(rootDir, "plugins/team-harness/hooks"), null],
    [join(rootDir, "docs"), join(rootDir, "plugins/team-harness/docs"), new Set(claudePackageDocs)],
  ];
  let stale = false;
  for (const [sourceRoot, targetRoot, allowlist] of projections) {
    const hooks = sourceRoot === join(rootDir, "hooks");
    // These are repository-owned package projections. The explicit boundary
    // keeps cleanup inside each generated tree and rejects a redirected target
    // before either stale removal or synchronization can touch it.
    await assertSafeDestinationPath(rootDir, targetRoot, "directory");
    const files = await walkFiles(sourceRoot);
    for (const [relativePath, targetBytes] of await walkFiles(targetRoot, targetRoot, { symbolicLinks: "include" })) {
      const generatedPath = allowlist === null || allowlist.has(relativePath);
      const scratchPath = hooks && isOpenCodeScratchBundle(relativePath);
      // A projection with an allowlist owns only those entries. Preserve
      // unrelated operator files that happen to share its package directory.
      if (!generatedPath && !scratchPath) continue;
      const symbolicLink = targetBytes === null;
      if (symbolicLink && isProjectedSourcePath(
        relativePath,
        files,
        allowlist,
        hooks ? isOpenCodeScratchBundle : undefined,
      )) {
        // A current projection must never be allowed to redirect reads or
        // writes, including when the link is a directory ancestor.
        await assertSafeDestinationPath(rootDir, join(targetRoot, relativePath), "file");
      }
      const presentInSource = files.has(relativePath) && generatedPath && !scratchPath;
      if (presentInSource) continue;
      stale = true;
      const target = join(targetRoot, relativePath);
      const reason = scratchPath
        ? "packaged local scratch bundle"
        : "stale Claude package asset missing canonical source";
      if (check) {
        process.stderr.write(`${reason}: ${relative(rootDir, target)}\n`);
        continue;
      }
      if (symbolicLink) await assertSafeLinkRemoval(rootDir, target);
      else await assertSafeDestinationPath(rootDir, target, "file");
      await rm(target);
    }
    for (const [relativePath, expected] of files) {
      if (allowlist !== null && !allowlist.has(relativePath)) continue;
      // OpenCode test bundles are local scratch output; the runtime ships raw TS.
      if (hooks && isOpenCodeScratchBundle(relativePath)) continue;
      const source = join(sourceRoot, relativePath);
      const target = join(targetRoot, relativePath);
      const sourceMode = (await lstat(source)).mode & 0o777;
      let current;
      let currentMode;
      try {
        current = await readFile(target);
        currentMode = (await lstat(target)).mode & 0o777;
      } catch (error) {
        if (error?.code !== "ENOENT") throw error;
      }
      if (current?.equals(expected) && currentMode === sourceMode) continue;
      stale = true;
      if (check) {
        process.stderr.write(`stale Claude package asset: ${relative(rootDir, target)}\n`);
        continue;
      }
      await assertSafeDestinationPath(rootDir, target, "file");
      await mkdir(dirname(target), { recursive: true });
      await writeFile(target, expected, { mode: sourceMode });
      await chmod(target, sourceMode);
    }
  }
  if (check && stale) throw new Error("Claude package assets are stale");
}

async function assertSafeDestinationPath(rootDir, target, leafKind) {
  const relativeTarget = relative(rootDir, target);
  if (relativeTarget === ".." || relativeTarget.startsWith(`..${sep}`)) {
    throw new Error(`shared pipeline destination escapes root: ${target}`);
  }
  const components = [rootDir];
  let current = rootDir;
  for (const part of relativeTarget.split(sep).filter(Boolean)) {
    current = join(current, part);
    components.push(current);
  }
  for (const [index, component] of components.entries()) {
    let stat;
    try {
      stat = await lstat(component);
    } catch (error) {
      if (error?.code === "ENOENT") continue;
      throw error;
    }
    if (stat.isSymbolicLink()) throw new Error(`refusing symbolic-link pipeline destination: ${component}`);
    const isLeaf = index === components.length - 1;
    if ((!isLeaf || leafKind === "directory") && !stat.isDirectory()) {
      throw new Error(`pipeline destination component is not a directory: ${component}`);
    }
    if (isLeaf && leafKind === "file" && !stat.isFile()) {
      throw new Error(`pipeline destination is not a regular file: ${component}`);
    }
  }
}

export async function syncSharedPipelineAssets({ check, rootDir }) {
  const sourceRoot = join(rootDir, "skills/pipeline/scripts");
  const targetRoots = [
    join(rootDir, "plugins/team-harness/skills/pipeline/scripts"),
    join(rootDir, "installer-assets/opencode-skills/pipeline/scripts"),
  ];
  let stale = false;
  for (const name of sharedPipelineScripts) {
    const source = join(sourceRoot, name);
    const expected = await readFile(source);
    for (const targetRoot of targetRoots) {
      const target = join(targetRoot, name);
      let current;
      try {
        await assertSafeDestinationPath(rootDir, target, "file");
        current = await readFile(target);
      } catch (error) {
        if (error?.code !== "ENOENT") throw error;
      }
      if (current?.equals(expected)) continue;
      stale = true;
      if (check) {
        process.stderr.write(`stale shared pipeline asset: ${relative(rootDir, target)}\n`);
        continue;
      }
      await assertSafeDestinationPath(rootDir, targetRoot, "directory");
      await mkdir(dirname(target), { recursive: true });
      await assertSafeDestinationPath(rootDir, target, "file");
      await writeFile(target, expected);
    }
  }
  for (const name of sharedPipelinePolicies) {
    const source = join(rootDir, "skills/pipeline", name);
    const expected = await readFile(source);
    for (const target of [
      join(rootDir, "plugins/team-harness/skills/pipeline", name),
      join(rootDir, "installer-assets/opencode-skills/pipeline", name),
    ]) {
      let current;
      try {
        await assertSafeDestinationPath(rootDir, target, "file");
        current = await readFile(target);
      } catch (error) {
        if (error?.code !== "ENOENT") throw error;
      }
      if (current?.equals(expected)) continue;
      stale = true;
      if (check) {
        process.stderr.write(`stale shared pipeline asset: ${relative(rootDir, target)}\n`);
        continue;
      }
      await mkdir(dirname(target), { recursive: true });
      await assertSafeDestinationPath(rootDir, target, "file");
      await writeFile(target, expected);
    }
  }
  if (check && stale) throw new Error("shared pipeline assets are stale");
}

export async function syncSkills({ check = false, rootDir = defaultRoot } = {}) {
  rootDir = resolve(rootDir);
  const names = await canonicalNames(rootDir);
  const codexGenerated = await syncProjection({
    check,
    rootDir,
    names,
    runtime: "codex",
    targetRoot: join(rootDir, "plugins/team-harness/skills"),
    overrides: codexOverrides,
  });
  const opencodeGenerated = await syncProjection({
    check,
    rootDir,
    names,
    runtime: "opencode",
    targetRoot: join(rootDir, "installer-assets/opencode-skills"),
    overrides: opencodeOverrides,
  });
  await syncSharedSetupAssets({ check, rootDir });
  await syncSharedPipelineAssets({ check, rootDir });
  await syncClaudePackageAssets({ check, rootDir });
  return { names, codexGenerated, opencodeGenerated };
}

if (process.argv[1] && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url))) {
  syncSkills({ check: process.argv.includes("--check") }).catch(error => {
    process.stderr.write(`${error.message}\n`);
    process.exitCode = 1;
  });
}
