#!/usr/bin/env node

import {
  chmod,
  lstat,
  mkdir,
  readFile,
  readdir,
  rm,
  writeFile,
} from "node:fs/promises";
import { dirname, join, relative, resolve, sep } from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const defaultRoot = resolve(fileURLToPath(new URL("../..", import.meta.url)));
const generatedMarker = "<!-- Code generated by tools/codex-runtime/sync-skills.mjs; DO NOT EDIT. -->";
const namePattern = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

// These skills have intentionally hand-authored Codex contracts. Every other
// canonical skill receives a generated runtime adapter and a packaged copy of
// its canonical workflow/resources.
export const codexOverrides = new Set([
  "deliver",
  "design",
  "implement",
  "init",
  "modes",
  "pipeline",
  "recover",
  "setup",
  "update",
  "validate",
]);

export const opencodeOverrides = new Set([
  "background",
  "cross-repo",
  "recover",
  "setup",
  "tmux",
  "update",
]);

const codexSpecialMappings = new Map([
  ["background", "Use Codex subagents for bounded background work. Never launch or require the `claude` binary."],
  ["clickup", "Store persistent values in the Codex-native Team Harness configuration. Preserve all opaque keys and never print credentials."],
  ["cross-repo", "Use only repository paths and external reads authorized by the operator. Delegate independent repositories only when the live request permits subagents."],
  ["diagram", "Create the diagram directly in Main using the packaged Excalidraw workflow; do not dispatch a Claude orchestrator."],
  ["d2-diagram", "Author the `.d2` source directly. Treat D2 CLI rendering as optional and report when the executable is unavailable."],
  ["excalidraw-diagram", "Use the packaged schema, templates, and renderer directly; preserve its render-validation loop when dependencies are available."],
  ["gcp-costs", "Default to read-only GCP inspection. Require native permission and explicit operator scope before any external command."],
  ["gcp-infra", "Keep read-and-plan as the default. For apply intent, use the available `security` and `qa` roles for review and require a fresh explicit operator approval before any mutation."],
  ["inline", "Treat inline as a Team Harness working preference only. It cannot change Codex's system collaboration mode, sandbox, or approval policy."],
  ["kg", "Use the configured Memory MCP when available; otherwise report the missing native dependency without substituting another store."],
  ["learn-english", "Read and update only the Codex-native Team Harness configuration through its packaged configuration helper."],
  ["likec4-diagram", "Author the `.c4` source directly. Treat LikeC4 rendering as optional and report when the CLI is unavailable."],
  ["lint", "Audit Codex plugin skills, generated agents, native hooks, and configuration paths; do not inspect or repair a Claude Code installation."],
  ["mcp-optimize", "Inspect Codex MCP registrations and config rather than Claude connector files. Preserve secrets and gate every proposed write."],
  ["obsidian-bases", "Resolve vault settings from Codex-native Team Harness configuration or explicit operator input, never from a Claude-only config path."],
  ["obsidian-cli", "Resolve vault settings from Codex-native Team Harness configuration or explicit operator input, never from a Claude-only config path."],
  ["pipelines", "Resolve workspace settings from the Codex-native Team Harness configuration and render state read-only."],
  ["research-code", "Use Codex explorers or other bounded subagents only when independent lanes are useful and allowed; Main consolidates all evidence."],
  ["save-session", "Resolve workspace settings from the Codex-native Team Harness configuration and preserve the confirmation gate."],
  ["resume-session", "Resolve workspace settings from the Codex-native Team Harness configuration and remain strictly read-only."],
  ["review-pr", "Use native GitHub capabilities or `gh`; preserve immutable snapshot capture and require approval before publishing review writes."],
  ["tmux", "When the operator explicitly requests external sessions, launch `codex`, never `claude`, and preserve native permission prompts and recoverable session naming."],
  ["todo", "Store persistent values in the Codex-native Team Harness configuration and preserve unrelated keys."],
  ["trace", "Resolve workspace and pricing settings from the Codex-native Team Harness configuration and remain read-only."],
]);

const opencodeSpecialMappings = new Map([
  ["bootstrap", "Initialize `AGENTS.md` and opencode-native project conventions unless the operator explicitly requests a Claude compatibility file."],
  ["clickup", "Store persistent values in the opencode-native Team Harness configuration. Preserve all opaque keys and never print credentials."],
  ["diagram", "Create the diagram through the packaged Excalidraw workflow; do not dispatch a Claude agent."],
  ["gcp-costs", "Default to read-only GCP inspection and require explicit scope before calling `gcloud`."],
  ["gcp-infra", "Keep read-and-plan as the default. Treat apply intent as gated and require a fresh explicit operator approval before mutation."],
  ["kg", "Use the configured Memory MCP when available; otherwise report the missing native dependency."],
  ["learn-english", "Read and update only the opencode-native Team Harness configuration."],
  ["lint", "Audit opencode-projected agents, skills, commands, and native configuration; do not inspect a Claude Code installation."],
  ["mcp-optimize", "Inspect opencode MCP registrations and configuration rather than Claude connector files."],
  ["obsidian-bases", "Resolve vault settings from opencode-native Team Harness configuration or explicit operator input."],
  ["obsidian-cli", "Resolve vault settings from opencode-native Team Harness configuration or explicit operator input."],
  ["pipelines", "Resolve workspace settings from opencode-native Team Harness configuration and render state read-only."],
  ["save-session", "Resolve workspace settings from opencode-native Team Harness configuration and preserve the confirmation gate."],
  ["resume-session", "Resolve workspace settings from opencode-native Team Harness configuration and remain read-only."],
  ["todo", "Store persistent values in opencode-native Team Harness configuration and preserve unrelated keys."],
  ["trace", "Resolve workspace and pricing settings from opencode-native Team Harness configuration and remain read-only."],
]);

const sharedPipelineScripts = [
  "bounded-command.mjs",
  "cleaner-transition.mjs",
  "plan-contract.mjs",
  "quality-runner.mjs",
  "test-transition.mjs",
];

function yamlString(value) {
  return JSON.stringify(value);
}

function humanize(name) {
  return name.split("-").map(part => part[0].toUpperCase() + part.slice(1)).join(" ");
}

function parseCanonicalSkill(bytes, expectedName) {
  const text = bytes.toString("utf8").replace(/^\uFEFF/, "").replace(/\r\n?/g, "\n");
  const match = text.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);
  if (!match) throw new Error(`invalid frontmatter: skills/${expectedName}/SKILL.md`);
  const fields = new Map();
  for (const line of match[1].split("\n")) {
    const field = line.match(/^([a-zA-Z0-9_-]+):\s*(.*)$/);
    if (!field) continue;
    let value = field[2].trim();
    if (value.startsWith('"') && value.endsWith('"')) value = value.slice(1, -1);
    fields.set(field[1], value);
  }
  if (fields.get("name") !== expectedName) {
    throw new Error(`skill name mismatch: ${expectedName} != ${fields.get("name")}`);
  }
  const description = fields.get("description");
  if (!description) throw new Error(`missing description: skills/${expectedName}/SKILL.md`);
  return {
    body: match[2].trimEnd(),
    description,
    explicitOnly: fields.get("disable-model-invocation") === "true",
  };
}

function renderAdapter(name, canonical, runtime) {
  const codex = runtime === "codex";
  const mapping = (codex ? codexSpecialMappings : opencodeSpecialMappings).get(name)
    ?? `Execute the capability directly with ${codex ? "Codex" : "opencode"}-native tools and the current permission policy.`;
  const invocation = codex ? `$team-harness:${name}` : name;
  const example = codex
    ? `Examples written as \`/th:${name}\` name the same capability; do not try to execute them as shell commands.`
    : `Examples written as \`/th:${name}\` name the same capability; interpret them as examples rather than requiring Claude Code.`;
  const configPath = codex
    ? "${CODEX_HOME:-$HOME/.codex}/.team-harness.json"
    : "${OPENCODE_CONFIG_DIR:-$HOME/.config/opencode}/.team-harness.json";
  const frontmatter = canonical.explicitOnly && !codex
    ? `---\nname: ${name}\ndescription: ${yamlString(canonical.description)}\nmetadata:\n  opencode/autoinvoke: "false"\n---`
    : `---\nname: ${name}\ndescription: ${yamlString(canonical.description)}\n---`;
  return `---
${frontmatter.slice(4)}

${generatedMarker}

# ${humanize(name)}

This is the ${codex ? "Codex" : "opencode"} projection of the canonical Team Harness \`${name}\`
workflow. Before acting, read \`canonical.md\` completely and load only the
supporting resources it routes to.

## ${codex ? "Codex" : "opencode"} runtime adapter

These rules override contradictory runtime-specific wording in the canonical
workflow:

1. Treat the live operator request for \`${invocation}\` as the canonical
   \`$ARGUMENTS\` value. ${example}
2. Keep the current primary thread as coordinator. A canonical instruction to
   invoke \`th:orchestrator\` means execute that routing decision in the current
   primary thread. Never spawn a persistent or nested orchestrator.
3. Translate Claude tool names to the closest native ${codex ? "Codex" : "opencode"} tools. Delegate
   only bounded work to available native agents when delegation is allowed and
   materially useful. Gate approval and consolidation stay in the primary thread.
4. Resolve persistent settings from
   \`${configPath}\`. Never depend on a Claude
   Code installation, \`~/.claude\`, the \`claude\` binary, or Claude plugin
   cache paths. Use packaged files relative to this skill directory.
5. Preserve every canonical safety boundary, read-only default, confirmation
   gate, secret rule, and outward-write approval. Native ${codex ? "Codex" : "opencode"} sandbox and
   permission policy remain authoritative.
6. ${mapping}

Execute the requested workflow after applying this adapter. Do not merely
summarize the canonical instructions.
`;
}

function renderOpenAI(name, canonical) {
  const short = `Team Harness ${humanize(name)} workflow`;
  return `interface:
  display_name: ${yamlString(`Team Harness ${humanize(name)}`)}
  short_description: ${yamlString(short.slice(0, 64))}
  default_prompt: ${yamlString(`Use $team-harness:${name} for this request.`)}
${canonical.explicitOnly ? "policy:\n  allow_implicit_invocation: false\n" : ""}`;
}

async function walkFiles(base, current = base) {
  const result = new Map();
  let entries;
  try {
    entries = await readdir(current, { withFileTypes: true });
  } catch (error) {
    if (error?.code === "ENOENT") return result;
    throw error;
  }
  entries.sort((a, b) => a.name.localeCompare(b.name));
  for (const entry of entries) {
    const absolute = join(current, entry.name);
    const rel = relative(base, absolute).split(sep).join("/");
    const stat = await lstat(absolute);
    if (stat.isSymbolicLink()) throw new Error(`refusing symbolic link: ${absolute}`);
    if (stat.isDirectory()) {
      if (entry.name === "__pycache__" || entry.name === "node_modules" || entry.name === ".venv") continue;
      for (const [child, bytes] of await walkFiles(base, absolute)) result.set(child, bytes);
    } else if (stat.isFile() && !entry.name.endsWith(".pyc")) {
      result.set(rel, await readFile(absolute));
    }
  }
  return result;
}

async function canonicalNames(rootDir) {
  const sourceRoot = join(rootDir, "skills");
  const entries = await readdir(sourceRoot, { withFileTypes: true });
  const names = [];
  for (const entry of entries) {
    if (!entry.isDirectory() || !namePattern.test(entry.name)) continue;
    try {
      const stat = await lstat(join(sourceRoot, entry.name, "SKILL.md"));
      if (stat.isFile()) names.push(entry.name);
    } catch (error) {
      if (error?.code !== "ENOENT") throw error;
    }
  }
  return names.sort();
}

async function expectedProjection(rootDir, name, runtime) {
  const sourceDir = join(rootDir, "skills", name);
  const sourceFiles = await walkFiles(sourceDir);
  const canonicalBytes = sourceFiles.get("SKILL.md");
  if (!canonicalBytes) throw new Error(`missing canonical skill: ${name}`);
  const canonical = parseCanonicalSkill(canonicalBytes, name);
  const expected = new Map([
    ["SKILL.md", Buffer.from(renderAdapter(name, canonical, runtime))],
    ["canonical.md", Buffer.from(`${canonical.body}\n`)],
  ]);
  if (runtime === "codex") {
    expected.set("agents/openai.yaml", Buffer.from(renderOpenAI(name, canonical)));
  }
  for (const [rel, bytes] of sourceFiles) {
    if (rel === "SKILL.md" || rel === "agents/openai.yaml") continue;
    expected.set(rel, bytes);
  }
  return expected;
}

async function isGenerated(targetDir) {
  try {
    const skill = await readFile(join(targetDir, "SKILL.md"), "utf8");
    return skill.includes(generatedMarker);
  } catch (error) {
    if (error?.code === "ENOENT") return false;
    throw error;
  }
}

async function projectionMatches(targetDir, expected) {
  const actual = await walkFiles(targetDir);
  if (actual.size !== expected.size) return false;
  for (const [rel, bytes] of expected) {
    if (!actual.get(rel)?.equals(bytes)) return false;
  }
  return true;
}

async function syncProjection({ check, rootDir, names, runtime, targetRoot, overrides }) {
  for (const override of overrides) {
    if (!names.includes(override)) throw new Error(`${runtime} override has no canonical skill: ${override}`);
  }

  let stale = false;
  for (const name of names) {
    if (overrides.has(name)) continue;
    const targetDir = join(targetRoot, name);
    const expected = await expectedProjection(rootDir, name, runtime);
    if (await projectionMatches(targetDir, expected)) continue;
    stale = true;
    if (check) {
      process.stderr.write(`stale ${runtime} skill: ${name}\n`);
      continue;
    }
    try {
      const stat = await lstat(targetDir);
      if (stat.isSymbolicLink() || !stat.isDirectory() || !(await isGenerated(targetDir))) {
        throw new Error(`refusing to replace unmanaged ${runtime} skill: ${targetDir}`);
      }
      await rm(targetDir, { recursive: true });
    } catch (error) {
      if (error?.code !== "ENOENT") throw error;
    }
    for (const [rel, bytes] of expected) {
      const target = join(targetDir, rel);
      await mkdir(dirname(target), { recursive: true });
      await writeFile(target, bytes);
    }
  }

  const targetEntries = await readdir(targetRoot, { withFileTypes: true });
  for (const entry of targetEntries) {
    if (!entry.isDirectory() || names.includes(entry.name)) continue;
    const targetDir = join(targetRoot, entry.name);
    if (!(await isGenerated(targetDir))) continue;
    stale = true;
    if (check) process.stderr.write(`stale generated skill: ${entry.name}\n`);
    else await rm(targetDir, { recursive: true });
  }

  if (check && stale) throw new Error(`${runtime} skill projections are stale`);
  return names.filter(name => !overrides.has(name));
}

async function syncSharedSetupAssets({ check, rootDir }) {
  const source = join(rootDir, "skills/setup/scripts/manage_github_identities.py");
  const bytes = await readFile(source);
  const targets = [
    join(rootDir, "plugins/team-harness/skills/setup/scripts/manage_github_identities.py"),
    join(rootDir, "installer-assets/opencode-skills/setup/scripts/manage_github_identities.py"),
  ];
  let stale = false;
  for (const target of targets) {
    let current;
    let currentMode;
    try {
      const [bytesAtTarget, targetStat] = await Promise.all([
        readFile(target),
        lstat(target),
      ]);
      current = bytesAtTarget;
      currentMode = targetStat.mode & 0o777;
    } catch (error) {
      if (error?.code !== "ENOENT") throw error;
    }
    const bytesMatch = current?.equals(bytes) ?? false;
    const modeMatches = currentMode === 0o755;
    if (bytesMatch && modeMatches) continue;
    stale = true;
    if (check) {
      const drift = [!bytesMatch && "content", !modeMatches && "mode"]
        .filter(Boolean)
        .join("+");
      process.stderr.write(`stale shared setup asset (${drift}): ${relative(rootDir, target)}\n`);
      continue;
    }
    await mkdir(dirname(target), { recursive: true });
    if (!bytesMatch) await writeFile(target, bytes, { mode: 0o755 });
    await chmod(target, 0o755);
  }
  if (check && stale) throw new Error("shared setup assets are stale");
}

async function assertSafeDestinationPath(rootDir, target, leafKind) {
  const relativeTarget = relative(rootDir, target);
  if (relativeTarget === ".." || relativeTarget.startsWith(`..${sep}`)) {
    throw new Error(`shared pipeline destination escapes root: ${target}`);
  }
  const components = [rootDir];
  let current = rootDir;
  for (const part of relativeTarget.split(sep).filter(Boolean)) {
    current = join(current, part);
    components.push(current);
  }
  for (const [index, component] of components.entries()) {
    let stat;
    try {
      stat = await lstat(component);
    } catch (error) {
      if (error?.code === "ENOENT") continue;
      throw error;
    }
    if (stat.isSymbolicLink()) throw new Error(`refusing symbolic-link pipeline destination: ${component}`);
    const isLeaf = index === components.length - 1;
    if ((!isLeaf || leafKind === "directory") && !stat.isDirectory()) {
      throw new Error(`pipeline destination component is not a directory: ${component}`);
    }
    if (isLeaf && leafKind === "file" && !stat.isFile()) {
      throw new Error(`pipeline destination is not a regular file: ${component}`);
    }
  }
}

export async function syncSharedPipelineAssets({ check, rootDir }) {
  const sourceRoot = join(rootDir, "skills/pipeline/scripts");
  const targetRoot = join(rootDir, "plugins/team-harness/skills/pipeline/scripts");
  await assertSafeDestinationPath(rootDir, targetRoot, "directory");
  let stale = false;
  for (const name of sharedPipelineScripts) {
    const source = join(sourceRoot, name);
    const target = join(targetRoot, name);
    const expected = await readFile(source);
    let current;
    try {
      await assertSafeDestinationPath(rootDir, target, "file");
      current = await readFile(target);
    } catch (error) {
      if (error?.code !== "ENOENT") throw error;
    }
    if (current?.equals(expected)) continue;
    stale = true;
    if (check) {
      process.stderr.write(`stale shared pipeline asset: ${relative(rootDir, target)}\n`);
      continue;
    }
    await assertSafeDestinationPath(rootDir, targetRoot, "directory");
    await mkdir(dirname(target), { recursive: true });
    await assertSafeDestinationPath(rootDir, target, "file");
    await writeFile(target, expected);
  }
  if (check && stale) throw new Error("shared pipeline assets are stale");
}

export async function syncSkills({ check = false, rootDir = defaultRoot } = {}) {
  rootDir = resolve(rootDir);
  const names = await canonicalNames(rootDir);
  const codexGenerated = await syncProjection({
    check,
    rootDir,
    names,
    runtime: "codex",
    targetRoot: join(rootDir, "plugins/team-harness/skills"),
    overrides: codexOverrides,
  });
  const opencodeGenerated = await syncProjection({
    check,
    rootDir,
    names,
    runtime: "opencode",
    targetRoot: join(rootDir, "installer-assets/opencode-skills"),
    overrides: opencodeOverrides,
  });
  await syncSharedSetupAssets({ check, rootDir });
  await syncSharedPipelineAssets({ check, rootDir });
  return { names, codexGenerated, opencodeGenerated };
}

if (process.argv[1] && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url))) {
  syncSkills({ check: process.argv.includes("--check") }).catch(error => {
    process.stderr.write(`${error.message}\n`);
    process.exitCode = 1;
  });
}
